### ISSUE TITLE
Integrating DialogRPT for Context-Specific Prompt-Based Response Evaluation

### ISSUE THREAD

**Issue by Mikeygoldman1** [golsun/DialogRPT#12]
Hi everyone. I am using DialogRPT to rank responses of a conversational AI model and I am finding the results very useful. However, the agent responds to users based on a specific prompt. I wanted to know if there is a way to use DialogRPT to rank the agent's responses based on this prompt?

**Comment by smmaker** [comment]
hi @Mikeygoldman1 , for ranking based on specific requirements/constraints, probably you could try to use GPT4 to do the ranking, and if it's too slow/expensive, probably you can try to train a DialogRPT based on GPT4 labels

**Comment by golsun** [comment]
hi @Mikeygoldman1 , for ranking based on specific requirements/constraints, probably you could try to use GPT4 to do the ranking, and if it's too slow/expensive, probably you can try to train a DialogRPT based on GPT4 labels
