### ISSUE TITLE
How context part is constructed? 

### ISSUE THREAD

**Issue by Rexhaif** [golsun/DialogRPT#2]
Hi, I've read the paper and repository description. But I'm still unsure how the context part of model input is constructed. So far I see two possible options:
* Context consist of only one conversation turn aka user's latest input
* Context is constructed in the way similar to DialoGPT and can contain multiple turns:
```
 'user_input' <|endoftext|> 'model_reply' <|endoftext|> 'user_input' <|endoftext|> ...<|endoftext|> 'user_input'
```
Can you clarify it?

**Comment by golsun** [comment]
Hi @Rexhaif 

DialogRPT supports multi-turn context, 

### For the original implementation
this repo uses `_EOS_` as delimiter, so context looks like
```
 'dialog-turn-1' _EOS_ 'dialog-turn-1' _EOS_ 'dialog-turn-1' _EOS_ ... _EOS_ 'dialog-turn-n'
```
If you want to use a different delimiter (e.g. `<|endoftext|>`, you can specify your own in [`src/shared.py`](https://github.com/golsun/DialogRPT/blob/master/src/shared.py), currently it's `EOS_token = '_EOS_'`.

### For Hugging Face model card
they use `<|endoftext|>`, for example: 
[I love NLP! <|endoftext|> Me too!](https://huggingface.co/microsoft/DialogRPT-updown?text=I+love+NLP%21+%3C%7Cendoftext%7C%3E+Me+too%21) (click it to see results by Hugging Face model card)

**Comment by Rexhaif** [comment]
Thanks!

**Comment by Mikeygoldman1** [comment]
'context_turn_1' <|endoftext|> 'context_turn_2' <|endoftext|> 'context_turn_3' <|endoftext|> ...<|endoftext|> 'context_turn_4'

In this case, is the model ranking 'context_turn_4' while taking into account all the previous contexts?
