### ISSUE TITLE
Is DialoGPT-medium required?

### ISSUE THREAD

**Issue by pablogranolabar** [golsun/DialogRPT#5]
Hola!

I am looking to integrate DialoGPT with DialogRPT-updown for conversational agent rank/re-ranking. From looking at Xiang Gao's model download function, DialoGPT medium model is being downloaded. So is DialoGPT-medium a requirement for DialoGPT+DialogRPT use or can DialoGPT-large be used?

TIA!

**Comment by golsun** [comment]
Hi @pablogranolabar 

Yes the default is DialoGPT-medium, but you can use DialoGPT-large or other generator

if you want to use DialoGPT-large, you need to 
* modify the model config [here](https://github.com/golsun/DialogRPT/blob/master/src/generation.py#L12), to `GPT2Config(n_embd=1280, n_layer=36, n_head=20)` (full details [here](https://huggingface.co/microsoft/DialoGPT-large/blob/main/config.json))
* then download DialoGPT-large
* then `python src/generation.py play -pg=path/to/DialoGPT-large.pkl -pr=restore/updown.pth --sampling`

**Comment by pablogranolabar** [comment]
One other question @golsun. How do these repos differ from the HuggingFace transformers variant? I've been testing DialoGPT with the chatbot example from the DialoGPT model card, but with DialoGPT-large instead of the default medium. Am I correct in assuming that DialogRPT from the transformers library is the same model architecture being based on GPT-2 and can be substituted for that chatbot example, as long as I load the DialoGPT checkpoint?

Thanks again for your help Xiang!

**Comment by golsun** [comment]
@pablogranolabar yes, they are the same checkpoint, the model implementation is slightly different though (this repo was based an older version of huggingface transformer) but shouldn't affect the results

**Comment by pablogranolabar** [comment]
Thanks @golsun. Another question, is gpt2-xl an option for this? As it looks like the only models supported by DialoGPT are medium and large?

**Comment by golsun** [comment]
hi @pablogranolabar you can use whatever dialogue generator you want to generate response candidates, and then use DialogRPT to rank them.
but DialogRPT was only trained to rank dialog responses, so GPT2-XL probably won't fit very well.

**Comment by pablogranolabar** [comment]
Thank you @golsun !
